Hw02 express
jfrasinska/goit-nodejs-homework pull request #1
Opened 2024-02-04 18:17 UTC by jfrasinska

2024-02-05 14:27 UTC, KamilMr requested changes
Dodaj validację jeszcze a pozatym to ładnie piszesz kod :)

2024-02-05 14:27 UTC, KamilMr commented on routes/api/contacts.json
> +    "id": "6616317860706a9c4453532fc475592f675f697bfab6eba16ce8a6f9e0977c24"
bardzo długie id ;)

2024-02-05 14:27 UTC, KamilMr commented on routes/api/contacts.js
> +  const { name, email, phone } = req.body;
Dodasz jescze validację poprzez Joi? Ustaw tam żeby te pola oprócz validacji to np tutaj powinny być required.

2024-02-05 14:27 UTC, KamilMr commented on routes/api/contacts.js
> +  const updatedFields = req.body;
To też trzeba zwalidować :)

2024-02-05 19:54 UTC, jfrasinska commented
Dodałam walidację, a czy to id stanowi problem?

2024-02-06 09:41 UTC, KamilMr approved these changes
Zatwierdzam :) A to id to narazie nie bo w sumie po tym wyszukujesz teraz.

2024-02-06 21:56 UTC, merged